spring:
  application:
    name: dexora
  datasource:
    url: jdbc:postgresql://localhost:5432/dexora_db
    username: postgres
    password: change_me

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true
